name: AuroraSounds
favicon: null
layout_spectrum: 0.66067
typography_spectrum: 0.6868
title: 'Soundtracks & Recording Studio'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1a617a'
    - '#40865f'
    - '#ffffff'
    - '#d6d6d6'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
